apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-yctqevos
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-yctqevos:42bb08ee0e122f7730a3ffe79097f3fc5d0d521a@sha256:561c4cad97962fa9c976f142472b882767553eb41a9b5513d9daea7936e6d7eb
          name: container-image
